; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32thing_plus
src_dir = src

[env:esp32thing_plus]
platform = espressif32
board = esp32thing_plus
framework = arduino
upload_port = /dev/tty.usbserial-110
monitor_speed = 115200
upload_speed = 115200

; Build options
build_type = debug

; Build flags - combined all options in one section
build_flags =
    -D CORE_DEBUG_LEVEL=5
    -D WIFI_CREDENTIALS_STORAGE=1
    -D HOMEDMX_WIFI_SSID='"${sysenv.HOMEDMX_WIFI_SSID}"'
    -D HOMEDMX_WIFI_PASS='"${sysenv.HOMEDMX_WIFI_PASS}"'
    -D HOMEDMX_SETUP_CODE='"${sysenv.HOMEDMX_SETUP_CODE}"'

; Monitor options
monitor_filters = esp32_exception_decoder, time

; Library dependencies
lib_deps =
    homespan/HomeSpan @ ^1.8.0
    sparkfun/SparkFun DMX Shield Library @ ^2.0.1
